apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: git-build-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: git-build-watcher
subjects:
- kind: ServiceAccount
  name: git-build-watcher
